In [1]:
import numpy as  np
import pandas as pd

In [2]:

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q'+df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    547     16   John  January      Q1
1  2023-01-02       B   West    811     45   Mary  January      Q1
2  2023-01-03       C  North    254     68    Bob  January      Q1
3  2023-01-04       D  South    839     68  Alice  January      Q1
4  2023-01-05       A   East    462     82   John  January      Q1
5  2023-01-06       B   West    744     89   Mary  January      Q1
6  2023-01-07       C  North    449     25    Bob  January      Q1
7  2023-01-08       D  South    952     90  Alice  January      Q1
8  2023-01-09       A   East    503     39   John  January      Q1
9  2023-01-10       B   West    790     21   Mary  January      Q1
10 2023-01-11       C  North    619     18    Bob  January      Q1
11 2023-01-12       D  South    386     12  Alice  January      Q1
12 2023-01-13       A   East    396     60   John  January      Q1
13 2023-01-14       B   West    628     67   Mary  January      Q1
14 2023-01-15       C  North    370     11    Bob  January      Q1
15 2023-01-16       D  South    279     22  Alice  January      Q1
16 2023-01-17       A   East    833     34   John  January      Q1
17 2023-01-18       B   West    755     15   Mary  January      Q1
18 2023-01-19       C  North    341     10    Bob  January      Q1
19 2023-01-20       D  South    974     60  Alice  January      Q1

In [3]:
pd.pivot_table(df,values = "Sales", index = 'Region', columns = "Product", aggfunc = 'median')

Product      A      B      C      D
Region
East     503.0    NaN    NaN    NaN
North      NaN    NaN  370.0    NaN
South      NaN    NaN    NaN  839.0
West       NaN  755.0    NaN    NaN

In [8]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index = 'Region' , columns = 'Product')

In [ ]:
pd.crosstab(df['Region'],df['Product'])   # In Pandas, crosstab() is used to count how many times combinations of values occur between two or more columns. So basically the crosstab consists of row and columns.

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0